from enum import Enum


class AccessibilityEnum(str, Enum):
    ALL = "ALL"
    ALL_TRANSFER_CRITICAL_HINT = "ALL_TRANSFER_CRITICAL_HINT"
    BOARDING_ALIGHTING_BY_CREW = "BOARDING_ALIGHTING_BY_CREW"
    BOARDING_ALIGHTING_BY_NOTIFICATION = "BOARDING_ALIGHTING_BY_NOTIFICATION"
    BOARDING_ALIGHTING_SELF = "BOARDING_ALIGHTING_SELF"
    BOARDING_ALIGHTING_SHUTTLE_TRANSPORT = "BOARDING_ALIGHTING_SHUTTLE_TRANSPORT"
    NONE = "NONE"

    def __str__(self) -> str:
        return str(self.value)
