from enum import Enum


class PTViaReferenceStatus(str, Enum):
    ALIGHTING_NOT_NECESSARY = "ALIGHTING_NOT_NECESSARY"
    BOARDING_ALIGHTING_NECESSARY = "BOARDING_ALIGHTING_NECESSARY"
    BOARDING_ALIGHTING_NOT_NECESSARY = "BOARDING_ALIGHTING_NOT_NECESSARY"
    BOARDING_NOT_NECESSARY = "BOARDING_NOT_NECESSARY"

    def __str__(self) -> str:
        return str(self.value)
