from enum import Enum


class StopV2AccessibilityMostRelevant(str, Enum):
    ALL = "ALL"
    BOARDING_ALIGHTING_BY_CREW = "BOARDING_ALIGHTING_BY_CREW"
    BOARDING_ALIGHTING_BY_NOTIFICATION = "BOARDING_ALIGHTING_BY_NOTIFICATION"
    BOARDING_ALIGHTING_NOT_POSSIBLE = "BOARDING_ALIGHTING_NOT_POSSIBLE"
    BOARDING_ALIGHTING_SELF = "BOARDING_ALIGHTING_SELF"
    BOARDING_ALIGHTING_SHUTTLE_TRANSPORT = "BOARDING_ALIGHTING_SHUTTLE_TRANSPORT"
    BOARDING_NEEDS_INFONOTE = "BOARDING_NEEDS_INFONOTE"
    BOARDING_NEEDS_RESERVATIONNOTE = "BOARDING_NEEDS_RESERVATIONNOTE"

    def __str__(self) -> str:
        return str(self.value)
