from enum import Enum


class TransportProductV2Category(str, Enum):
    BUS_COACH_TAXI = "BUS_COACH_TAXI"
    CABLEWAY_FUNICULAR_GONDOLALIFT_CHAIRLIFT = "CABLEWAY_FUNICULAR_GONDOLALIFT_CHAIRLIFT"
    EUROCITY_INTERCITY_ICN_INTERCITYNIGHT_SUPERCITY = "EUROCITY_INTERCITY_ICN_INTERCITYNIGHT_SUPERCITY"
    FASTTRAIN_REGIOEXPRESS = "FASTTRAIN_REGIOEXPRESS"
    ICE_EN_CNL_CIS_ES_MET_NZ_PEN_TGV_THA_X2 = "ICE_EN_CNL_CIS_ES_MET_NZ_PEN_TGV_THA_X2"
    INTERREGIO = "INTERREGIO"
    METRO_MOTORAILTRAIN_SPECIALTRAIN_URLAUBSEXPRESS = "METRO_MOTORAILTRAIN_SPECIALTRAIN_URLAUBSEXPRESS"
    SHIP_FERRY_STEAMER = "SHIP_FERRY_STEAMER"
    TRAMWAY = "TRAMWAY"
    URBANRAILWAY_STADTEXPRESS_SEMIFASTTRAIN_OMNIBUSTRAIN = "URBANRAILWAY_STADTEXPRESS_SEMIFASTTRAIN_OMNIBUSTRAIN"

    def __str__(self) -> str:
        return str(self.value)
